ACCELERATE:
  RUN_NAME: "clip_model"
  EVAL_PERIOD: 10

MODEL:
  COND_STAGE_CONFIG:
    DEPTHS: []

  APPEARANCE_GUIDANCE_CONFIG:
    ATTN_RESIDUAL_BLOCK_IDX: []
    INNER_DIMS: []
    CTX_DIMS: []
    EMBED_DIMS: []
    HEADS: []
    CONVIN_KERNEL_SIZE: []
    CONVIN_STRIDE: []
    CONVIN_PADDING: []

  DECODER_CONFIG:
    N_CTX: 1
    DEPTH: 0

INPUT:
  COND:
    IMG_SIZE: [224, 224]