ACCELERATE:
  RUN_NAME: "no_app"
  EVAL_PERIOD: 10

MODEL:
  APPEARANCE_GUIDANCE_CONFIG:
    ATTN_RESIDUAL_BLOCK_IDX: []
    INNER_DIMS: []
    CTX_DIMS: []
    EMBED_DIMS: []
    HEADS: []
    CONVIN_KERNEL_SIZE: []
    CONVIN_STRIDE: []
    CONVIN_PADDING: []