MODEL:
  COND_STAGE_CONFIG:
    PRETRAINED_PATH: "pretrained_models/swin/swin_base_patch4_window12_384_22kto1k.pth"
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 16
    DROP_PATH_RATE: 0.2

  APPEARANCE_GUIDANCE_CONFIG:
    CONVIN_KERNEL_SIZE: 1
    CONVIN_STRIDE: 1
    CONVIN_PADDING: 0
    ATTN_RESIDUAL_BLOCK_IDX: [11, 10, 9, 8, 7, 6, 5, 4, 3]
    INNER_DIMS: [128, 128, 128, 256, 256, 256, 512, 512, 512]
    CTX_DIMS: [320, 320, 320, 640, 640, 640, 1280, 1280, 1280]
    EMBED_DIMS: [64, 64, 64, 128, 128, 128, 256, 256, 256]
    HEADS: [2, 2, 2, 4, 4, 4, 8, 8, 8]
    DEPTH: 4

INPUT:
  COND:
    IMG_SIZE: [512, 512]

TEST:
  IMG_SIZE: [512, 352]