MODEL:
  COND_STAGE_CONFIG:
    PRETRAINED_PATH: "pretrained_models/swin/swin_large_patch4_window12_384_22kto1k.pth"
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 16
    DROP_PATH_RATE: 0.2

  APPEARANCE_GUIDANCE_CONFIG:
    CONVIN_KERNEL_SIZE: 3
    CONVIN_STRIDE: 2
    CONVIN_PADDING: 1
    ATTN_RESIDUAL_BLOCK_IDX: [11, 10, 9, 8, 7, 6, 5, 4, 3]
    INNER_DIMS: [192, 192, 192, 384, 384, 384, 768, 768, 768]
    CTX_DIMS: [320, 320, 320, 640, 640, 640, 1280, 1280, 1280]
    EMBED_DIMS: [96, 96, 96, 192, 192, 192, 384, 384, 384]
    HEADS: [3, 3, 3, 6, 6, 6, 12, 12, 12]
    DEPTH: 4

INPUT:
  COND:
    IMG_SIZE: [512, 512]

TEST:
  IMG_SIZE: [512, 352]